# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 07:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdtm', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(verbose_name='Amount')),
            ],
        ),
        migrations.CreateModel(
            name='CTFProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctfcount', models.IntegerField(help_text='How many CTFs have you participated in?', null=True, verbose_name='CTF Count History')),
                ('confidence', models.CharField(help_text='How confident are you that you will win?', max_length=2048, null=True, verbose_name='Confidence Level')),
                ('skills', models.CharField(help_text='What skills can you bring to your team?', max_length=2048, null=True, verbose_name='Skills')),
                ('training', models.CharField(help_text='What types of training have you taken?', max_length=2048, null=True, verbose_name='Training Taken')),
                ('wallet', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slogan', models.CharField(blank=True, default='', max_length=2048, null=True)),
                ('user1', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('user2', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('user3', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('odds', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.AddField(
            model_name='ctfprofile',
            name='team',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='prospect.Teams'),
        ),
        migrations.AddField(
            model_name='ctfprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bet',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospect.Teams'),
        ),
        migrations.AddField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
